In [34]:
import datetime
from pathlib import Path
import pysacsnow

In [35]:
base_dir = Path('/home/kvanwerkhoven/projects/pysac')
region = 'hawaii'

study_dir = Path(base_dir, region)
data_dir = Path(study_dir, 'data')
read_dir = Path(study_dir, 'pyMARRMot_input')
forcing_dir = Path(data_dir, 'forcing')
obs_dir = Path(data_dir, 'observations')

In [16]:
# file = Path(base_dir, 'hawaii/data/nwm.20230918_forcing_analysis_assim_hawaii_nwm.t23z.analysis_assim.forcing.tm02.hawaii.nc')
# file1 = Path(base_dir, 'hawaii/data/nwm.20230919_forcing_analysis_assim_hawaii_nwm.t00z.analysis_assim.forcing.tm00.hawaii.nc')
# file2 = Path(base_dir, 'hawaii/data/nwm.20230919_forcing_analysis_assim_hawaii_nwm.t10z.analysis_assim.forcing.tm00.hawaii.nc')
# file3 = Path(base_dir, 'hawaii/data/nwm.20230919_forcing_analysis_assim_hawaii_nwm.t11z.analysis_assim.forcing.tm00.hawaii.nc')
# file4 = Path(base_dir, 'hawaii/data/nwm.20230919_forcing_analysis_assim_hawaii_nwm.t12z.analysis_assim.forcing.tm00.hawaii.nc')
# file5 = Path(base_dir, 'hawaii/data/nwm.20230919_forcing_analysis_assim_hawaii_nwm.t13z.analysis_assim.forcing.tm00.hawaii.nc')
# file7 = Path(base_dir, 'hawaii/data/nwm.20230919_forcing_analysis_assim_hawaii_nwm.t14z.analysis_assim.forcing.tm00.hawaii.nc')
# file8 = Path(base_dir, 'hawaii/data/nwm.20230919_forcing_analysis_assim_hawaii_nwm.t15z.analysis_assim.forcing.tm00.hawaii.nc')
# file9 = Path(base_dir, 'hawaii/data/nwm.20230919_forcing_analysis_assim_hawaii_nwm.t16z.analysis_assim.forcing.tm00.hawaii.nc')

# file10 = Path(base_dir, 'hawaii/data/nwm.20230919_forcing_analysis_assim_puertorico_nwm.t10z.analysis_assim.forcing.tm00.puertorico.nc')
# file11 = Path(base_dir, 'hawaii/data/nwm.20230919_forcing_analysis_assim_puertorico_nwm.t11z.analysis_assim.forcing.tm00.puertorico.nc')
# file12 = Path(base_dir, 'hawaii/data/nwm.20230919_forcing_analysis_assim_puertorico_nwm.t12z.analysis_assim.forcing.tm00.puertorico.nc')
# file13 = Path(base_dir, 'hawaii/data/nwm.20230919_forcing_analysis_assim_puertorico_nwm.t13z.analysis_assim.forcing.tm00.puertorico.nc')
# file14 = Path(base_dir, 'hawaii/data/nwm.20230919_forcing_analysis_assim_puertorico_nwm.t14z.analysis_assim.forcing.tm00.puertorico.nc')

# file12 = Path(base_dir, 'hawaii/data/nwm.20230919_forcing_analysis_assim_alaska_nwm.t13z.analysis_assim.forcing.tm00.alaska.nc')
# file13 = Path(base_dir, 'hawaii/data/nwm.20230919_forcing_analysis_assim_alaska_nwm.t14z.analysis_assim.forcing.tm00.alaska.nc')

# file14 = Path(base_dir, 'hawaii/data/nwm.20230919_forcing_analysis_assim_nwm.t13z.analysis_assim.forcing.tm00.conus.nc')
# file15 = Path(base_dir, 'hawaii/data/nwm.20230919_forcing_analysis_assim_nwm.t14z.analysis_assim.forcing.tm00.conus.nc')

file12 = Path(base_dir, 'hawaii/data/nwm.20230919_forcing_analysis_assim_nwm.t12z.analysis_assim.forcing.tm00.conus.nc')
file13 = Path(base_dir, 'hawaii/data/nwm.20230919_forcing_analysis_assim_nwm.t13z.analysis_assim.forcing.tm00.conus.nc')
file14 = Path(base_dir, 'hawaii/data/nwm.20230919_forcing_analysis_assim_nwm.t14z.analysis_assim.forcing.tm00.conus.nc')
file15 = Path(base_dir, 'hawaii/data/nwm.20230919_forcing_analysis_assim_nwm.t15z.analysis_assim.forcing.tm00.conus.nc')
file16 = Path(base_dir, 'hawaii/data/nwm.20230919_forcing_analysis_assim_nwm.t16z.analysis_assim.forcing.tm00.conus.nc')
file17 = Path(base_dir, 'hawaii/data/nwm.20230919_forcing_analysis_assim_nwm.t17z.analysis_assim.forcing.tm00.conus.nc')

In [17]:
# 9-18-2023 t23z v2.2
# 9-19-2023 t00z v2.2
# 9-19-2023 t10z v2.2
# 9-19-2023 t11z v2.2
# 9-19-2023 t12z v2.2


# Hawaii
# 9-19-2023 t13z v2.2
# 9-19-2023 t14z v3.0

# puertorico
# 9-19-2023 t11z v2.2
# 9-19-2023 t12z v3.0

# conus
# 9-19-2023 t16z v2.2
# 9-19-2023 t17z v3.0

In [18]:
import xarray as xr

In [19]:
ds = xr.open_dataset(file17)
ds

<xarray.Dataset> Size: 1GB
Dimensions:         (time: 1, y: 3840, x: 4608, reference_time: 1)
Coordinates:
  * time            (time) datetime64[ns] 8B 2023-09-19T17:00:00
  * y               (y) float64 31kB -1.92e+06 -1.919e+06 ... 1.919e+06
  * x               (x) float64 37kB -2.303e+06 -2.302e+06 ... 2.304e+06
  * reference_time  (reference_time) datetime64[ns] 8B 2023-09-19T17:00:00
Data variables:
    crs             |S1 1B ...
    U2D             (time, y, x) float64 142MB ...
    V2D             (time, y, x) float64 142MB ...
    LWDOWN          (time, y, x) float64 142MB ...
    RAINRATE        (time, y, x) float32 71MB ...
    T2D             (time, y, x) float64 142MB ...
    Q2D             (time, y, x) float64 142MB ...
    PSFC            (time, y, x) float64 142MB ...
    SWDOWN          (time, y, x) float64 142MB ...
Attributes:
    model_output_valid_time:    2023-09-19_17:00:00
    model_initialization_time:  2023-09-19_14:00:00
    NWM_version_number:         v3.0
    model_configuration:        analysis_assim
    model_output_type:          forcing
    model_total_valid_times:    3
    Conventions:                CF-1.5
    GDAL_DataType:              Generic
    proj4:                      +proj=lcc +units=m +a=6370000.0 +b=6370000.0 ...
    region:                     CONUS

In [36]:
pysacsnow.model_utils.create_new_models(study_dir)
obs_dir.mkdir(parents=True, exist_ok=True)

Created folder: /home/kvanwerkhoven/projects/pysac/hawaii/data/forcing
Created folder: /home/kvanwerkhoven/projects/pysac/hawaii/data/output
Created folder: /home/kvanwerkhoven/projects/pysac/hawaii/configurations/sac
Created folder: /home/kvanwerkhoven/projects/pysac/hawaii/configurations/snow17
Created folder: /home/kvanwerkhoven/projects/pysac/hawaii/configurations/unithg
Created folder: /home/kvanwerkhoven/projects/pysac/hawaii/configurations/multi-model

In [37]:
# Check if folders were created
for p in study_dir.rglob('*'):
    if p.is_dir():
        print(p)

/home/kvanwerkhoven/projects/pysac/hawaii/pyMARRMot_input
/home/kvanwerkhoven/projects/pysac/hawaii/configurations
/home/kvanwerkhoven/projects/pysac/hawaii/data
/home/kvanwerkhoven/projects/pysac/hawaii/.ipynb_checkpoints
/home/kvanwerkhoven/projects/pysac/hawaii/output
/home/kvanwerkhoven/projects/pysac/hawaii/notebooks
/home/kvanwerkhoven/projects/pysac/hawaii/pyMARRMot_input/pysac_input
/home/kvanwerkhoven/projects/pysac/hawaii/pyMARRMot_input/.ipynb_checkpoints
/home/kvanwerkhoven/projects/pysac/hawaii/configurations/snow17
/home/kvanwerkhoven/projects/pysac/hawaii/configurations/.ipynb_checkpoints
/home/kvanwerkhoven/projects/pysac/hawaii/configurations/unithg
/home/kvanwerkhoven/projects/pysac/hawaii/configurations/sac
/home/kvanwerkhoven/projects/pysac/hawaii/configurations/multi-model
/home/kvanwerkhoven/projects/pysac/hawaii/data/observations
/home/kvanwerkhoven/projects/pysac/hawaii/data/.ipynb_checkpoints
/home/kvanwerkhoven/projects/pysac/hawaii/data/output
/home/kvanwerkhoven/projects/pysac/hawaii/data/forcing
/home/kvanwerkhoven/projects/pysac/hawaii/notebooks/.ipynb_checkpoints
/home/kvanwerkhoven/projects/pysac/hawaii/notebooks/__pycache__
/home/kvanwerkhoven/projects/pysac/hawaii/pyMARRMot_input/pysac_input/.ipynb_checkpoints
/home/kvanwerkhoven/projects/pysac/hawaii/configurations/unithg/.ipynb_checkpoints
/home/kvanwerkhoven/projects/pysac/hawaii/configurations/sac/.ipynb_checkpoints
/home/kvanwerkhoven/projects/pysac/hawaii/configurations/multi-model/.ipynb_checkpoints
/home/kvanwerkhoven/projects/pysac/hawaii/data/observations/.ipynb_checkpoints
/home/kvanwerkhoven/projects/pysac/hawaii/data/output/.ipynb_checkpoints
/home/kvanwerkhoven/projects/pysac/hawaii/data/forcing/.ipynb_checkpoints

In [38]:
import pandas as pd
from pathlib import Path

In [39]:
usgs_ids = {
    f.name.split("_")[0]
    for f in read_dir.glob("usgs-*.parquet")
}
usgs_ids = sorted(usgs_ids)

In [41]:
usgs_ids = sorted(usgs_ids)
df = pd.read_parquet(Path(base_dir, 'usgs_point_attr_drainage_area.all.parquet'))
df_areas = df[df['location_id'].isin(usgs_ids)]

area_km2 = df_areas.loc[df_areas['location_id'] == location_id, 'value'].item()

In [44]:
for usgs_id in usgs_ids:

    usgs_num = usgs_id.split("-")[1]
    filename = f'{usgs_id}_combined_extana.parquet'
    df = pd.read_parquet(Path(read_dir, filename))
    df["value_time"] = pd.to_datetime(df["value_time"])
    df = df.set_index("value_time")
    
    # Create full hourly time range
    full_index = pd.date_range(
        start=df.index.min(),
        end=df.index.max(),
        freq="h"
    )
    # Reindex to full range (this inserts missing timestamps)
    df = df.reindex(full_index)
    # Fill missing values by column
    df["precip_mm"] = df["precip_mm"].fillna(0)
    df["pet_mm"] = df["pet_mm"].fillna(0)
    # If you want datetime back as a column
    df = df.reset_index().rename(columns={"index": "time"})
    
    df_sac = df[['time','precip_mm','pet_mm']].rename(columns={'precip_mm':'hru_ppt','pet_mm':'hru_pet'})
    
    # round data to 3 decimals
    df_sac['hru_ppt'] = df_sac['hru_ppt'].round(4)
    df_sac['hru_pet'] = df_sac['hru_pet'].round(4)
    df_sac.to_csv(Path(forcing_dir, f'forcing.sac.{usgs_num}.csv'))

    # create uh forcing (all zero)
    df_uhg = df_sac.copy().rename(columns={'hru_ppt':'hru_tci'}).drop('hru_pet', axis=1)
    df_uhg['hru_tci'] = 0
    df_uhg.to_csv(Path(forcing_dir, f'forcing.uhg.{usgs_num}.csv'))

    # get area
    area_km2 = df_areas.loc[df_areas['location_id'] == usgs_id, 'value'].item()
    
    # create obs 
    df_obs = df[['time','obs_flow_mm']].rename(columns={'obs_flow_mm':'QIN_cms'})
    df_obs['QIN_cms'] = df_obs['QIN_cms'] * area_km2 * 1000 / 3600
    df_obs = df_obs.set_index('time')
    df_obs.to_csv(Path(obs_dir, f'QIN_{usgs_num}.csv'))

    print(usgs_id, area_km2)

usgs-16010000 9.89
usgs-16019000 5.41
usgs-16060000 61.48
usgs-16068000 16.16
usgs-16071500 1.94
usgs-16097500 3.11
usgs-16103000 47.94
usgs-16108000 27.04
usgs-16200000 3.57
usgs-16208000 10.62
usgs-16211600 5.48
usgs-16212490 27.45
usgs-16212601 17.4
usgs-16226200 10.41
usgs-16227500 2.38
usgs-16229000 6.63
usgs-16238000 6.4
usgs-16238500 2.9
usgs-16240500 2.72
usgs-16244000 2.98
usgs-16254000 5.26
usgs-16275000 2.49
usgs-16283200 2.15
usgs-16284200 2.51
usgs-16294100 9.87
usgs-16294900 5.8
usgs-16296500 9.66
usgs-16301050 7.17
usgs-16304200 2.82
usgs-16325000 8.16
usgs-16345000 7.77
usgs-16400000 12.12
usgs-16414200 18.93
usgs-16415600 13.67
usgs-16501200 22.09
usgs-16508000 8.52
usgs-16518000 9.3
usgs-16552800 6.47
usgs-16587000 1.53
usgs-16604500 15.88
usgs-16614000 11.06
usgs-16618000 8.81
usgs-16620000 10.83
usgs-16717000 31.18
usgs-16720000 3.99
usgs-16725000 2.15
usgs-16756100 6.42
usgs-16758000 3.63
usgs-16759600 28.23
usgs-16770500 4.3

In [36]:
import numpy as np

In [38]:
ts = np.timedelta64(3600, 's')

In [39]:
ts

np.timedelta64(3600,'s')

In [40]:
(df_sac['time'].max() - df_sac['time'].min()) / ts

43656.0

In [41]:
(datetime.datetime(2026, 4, 12, 0, 0) - datetime.datetime(2021, 4, 20, 0, 0)) / ts

43632.0

In [ ]:
(self._end_time - self._start_time) / self._time_step

In [17]:
df_sac[df_sac['time'].duplicated()]

Empty DataFrame
Columns: [time, hru_ppt, hru_pet]
Index: []

In [12]:
df_sac[df_sac['hru_pet'].isna()]

Empty DataFrame
Columns: [time, hru_ppt, hru_pet]
Index: []

In [10]:
df_uhg

                     time  hru_tci
0     2021-04-19 22:00:00        0
1     2021-04-19 23:00:00        0
2     2021-04-20 00:00:00        0
3     2021-04-20 01:00:00        0
4     2021-04-20 02:00:00        0
...                   ...      ...
43629 2026-04-12 18:00:00        0
43630 2026-04-12 19:00:00        0
43631 2026-04-12 20:00:00        0
43632 2026-04-12 21:00:00        0
43633 2026-04-12 22:00:00        0

[43634 rows x 2 columns]

In [25]:
df_obs

                     QIN
time
2021-04-19 22:00:00  NaN
2021-04-19 23:00:00  NaN
2021-04-20 00:00:00  0.0
2021-04-20 01:00:00  0.0
2021-04-20 02:00:00  0.0
...                  ...
2026-04-12 18:00:00  0.0
2026-04-12 19:00:00  0.0
2026-04-12 20:00:00  0.0
2026-04-12 21:00:00  0.0
2026-04-12 22:00:00  0.0

[43634 rows x 1 columns]